// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTf2Lb-gBXwHnTOLE4W7jU6wB_vJZq94',
    appId: '1:1094232275889:web:1074247885c93ae3bddb90',
    messagingSenderId: '1094232275889',
    projectId: 'chat-2496f',
    authDomain: 'chat-2496f.firebaseapp.com',
    databaseURL: 'https://chat-2496f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-2496f.appspot.com',
    measurementId: 'G-CBYGTVW6K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxcE_H6mLWI4zne7MP0kZ3dvsD3MZLZw8',
    appId: '1:1094232275889:android:79b0be408f655810bddb90',
    messagingSenderId: '1094232275889',
    projectId: 'chat-2496f',
    databaseURL: 'https://chat-2496f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-2496f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdDZ1AaHX9cZEkST3L6PwHaspz3ur6fr4',
    appId: '1:1094232275889:ios:bf6eef17ea8b08b0bddb90',
    messagingSenderId: '1094232275889',
    projectId: 'chat-2496f',
    databaseURL: 'https://chat-2496f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-2496f.appspot.com',
    iosBundleId: 'com.example.sketcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdDZ1AaHX9cZEkST3L6PwHaspz3ur6fr4',
    appId: '1:1094232275889:ios:bf6eef17ea8b08b0bddb90',
    messagingSenderId: '1094232275889',
    projectId: 'chat-2496f',
    databaseURL: 'https://chat-2496f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-2496f.appspot.com',
    iosBundleId: 'com.example.sketcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvTf2Lb-gBXwHnTOLE4W7jU6wB_vJZq94',
    appId: '1:1094232275889:web:3258133b30f4c796bddb90',
    messagingSenderId: '1094232275889',
    projectId: 'chat-2496f',
    authDomain: 'chat-2496f.firebaseapp.com',
    databaseURL: 'https://chat-2496f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-2496f.appspot.com',
    measurementId: 'G-Y6XERWMCZ9',
  );
}
